# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


# Practical_6: Numpy



# Exercise 1:¶

Create a NumPy array of integers from 1 to 10.

In [5]:
import numpy as np
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


# Exercise 2:

Create a 3x3 NumPy array filled with zeros.

In [9]:
x = np.zeros([3,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
x.dtype

dtype('float64')

# Exercise 3:

Create a NumPy array of 10 evenly spaced numbers between 0 and 5.



In [11]:
x = np.linspace(0,5,10)
x

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Exercise 4:

Create a 5x5 identity matrix using NumPy.



In [12]:
x = np.eye(5,5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Exercise 5:

Create a 4x4 matrix with random values between 0 and 1.

In [13]:
x = np.random.rand(4,4)
x

array([[0.40966882, 0.50492357, 0.55639798, 0.35803823],
       [0.40372414, 0.92382998, 0.44231549, 0.25717684],
       [0.38441208, 0.58495311, 0.93511267, 0.69851872],
       [0.77712708, 0.73743156, 0.72491147, 0.78820768]])

In [16]:
x = np.random.random((4,4))
x

array([[0.10604768, 0.77245157, 0.23988386, 0.92012486],
       [0.37579267, 0.59173113, 0.60390608, 0.76029994],
       [0.91102083, 0.80914358, 0.11230853, 0.41135542],
       [0.13269371, 0.94996792, 0.33461881, 0.08131445]])

In [17]:
x = np.random.seed(10)
x

In [19]:
x = np.random.rand(4,4)
x

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [21]:
x = np.random.seed(0)
x

In [22]:
x = np.random.rand(4,4)
x

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

# Exercise 6:

Find the shape of a NumPy array.

In [23]:
x.shape

(4, 4)

# Exercise 7:

Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.



In [28]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
x.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Exercise 8:

Find the data type of the elements in a NumPy array.

In [30]:
x.dtype

dtype('int64')

# Exercise 9:

Create a NumPy array of integers from 1 to 100 and find all even numbers in the array

In [24]:
x = [y for y in np.arange(1,101) if y % 2 == 0]
x

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [25]:
x = np.arange(2,101,2)
x

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# xercise 10:

Generate a 6x6 matrix of random integers between 10 and 50.



In [26]:
x = np.random.randint(10, 50, (6,6))
x

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])


# Exercise 11:

Slice a 2D NumPy array to extract a submatrix.

In [40]:
x = np.random.rand(2,2)
x[0,:]

array([0.97958673, 0.35944446])

In [44]:
y = np.array([[1,2],[3,4]])
print(y)

[[1 2]
 [3 4]]


In [49]:
y[1,1]

4

In [46]:
y[1,:]

array([3, 4])

# Exercise 12:

Calculate the sum of all elements in a NumPy array.

In [50]:
y.sum()

10

# Exercise 13:

Calculate the mean, median, and standard deviation of a NumPy array.

In [56]:
np.mean(y)

2.5

In [57]:
np.median(y)

2.5

In [58]:
y.std()

1.118033988749895

# Exercise 14:

Find the maximum and minimum values in a NumPy array.

In [59]:
y.max()

4

In [60]:
y.min()

1

# Exercise 15:

Create a NumPy array of 20 random integers and find the index of the maximum value.

In [65]:
x = np.random.randint(20, size = 20)
x

array([11, 16, 14, 16, 19,  1,  8,  0,  4,  6, 13,  7, 15,  9, 18,  8, 15,
       11,  6, 15])

In [66]:
np.argmax(x)

4

In [67]:
np.argmin(x)

7

# Exercise 16:

Create a NumPy array and reverse its elements.

In [68]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
z = list(reversed(y))
print(z)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


# Exercise 17:

Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[4,7,8],[3,2,0], [5,4,3]])
z = np.dot(x, y)
print(z)

[[ 25  23  17]
 [ 61  62  50]
 [ 97 101  83]]


# Exercise 18:

Create a diagonal matrix from a given 1D array.



In [4]:
import numpy as np
x = np.array([4,5,6])
z = np.diag(x)
print(z)

[[4 0 0]
 [0 5 0]
 [0 0 6]]


# Exercise 19:

Perform matrix multiplication on two 2D NumPy arrays.



In [9]:
x = np.array([[4,5],[3,2]])
y = np.array([[5,5],[4,7]])
z = np.dot(x, y)
print(z)

[[40 55]
 [23 29]]


# Exercise 20:

Flatten a 2D NumPy array into a 1D array.

In [16]:
x = np.array([[2,4,5],[5,9,0]])
z = np.ravel(x)
print(z)

[2 4 5 5 9 0]
